apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: "{{ .Values.namespace }}"
  labels:
    app: techtrends

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: york42/techtrends:latest
          name: techtrends
          resources: {{- toYaml .Values.resources | nindent 12}}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          redinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          ports: {{.Values.containerPort}}
