apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: "{{ .Values.namespace }}"
  labels:
    app: techtrends

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: york42/techtrends:latest
          name: techtrends
          resources: 
            {{ toYaml .Values.resources | indent 12}}
          livenessProbe: 
            {{ toYaml .Values.livenessProbe | indent 12 }}
          redinessProbe: 
            {{ toYaml .Values.readinessProbe | indent 12 }}
          ports: 
            {{ toYaml .Values.containerPort | indent 13 }}
