apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
  ports:
    - name: app-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
