apiVersion: v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: techtrends
    spec:
      containers:
        - image: york42/techtrends:latest
          name: techtrends
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3111
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3111
          ports:
            - containerPort: 3111
