kind: Service
apiVersion: v1
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
  type: ClusterIP
  ports:
    - name: app-port
      protocol: TCP
      port: 4111
      targetPort: 3111
